services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    #twig extensions
    library.twig.twig_extension:
        class: LibraryBundle\Twig\LibraryExtension
        tags:
            - { name: twig.extension }

    library.listener:
        class: LibraryBundle\EventListener\LibrarySubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            - '%cover_directory%'
            - '%book_directory%'
            - '%cache_books_id%'
            - '@cache_books_service'

    library.form_trans:
        class: LibraryBundle\Form\BookType
        arguments:
            - '%locale%'

    cache_books_service:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments:
            - '%cache_dir%'
        public: true
