book_index:
    path:     /
    defaults: { _controller: "LybraryBundle:Book:index" }
    methods:  GET

book_show:
    path:     /{id}/show
    defaults: { _controller: "LybraryBundle:Book:show" }
    methods:  GET

book_new:
    path:     /new
    defaults: { _controller: "LybraryBundle:Book:new" }
    methods:  [GET, POST]

book_edit:
    path:     /{id}/edit
    defaults: { _controller: "LybraryBundle:Book:edit" }
    methods:  [GET, POST]
    requirements:
        id: \d+

book_delete:
    path:     /{id}/delete
    defaults: { _controller: "LybraryBundle:Book:delete" }
    methods:  [GET, DELETE]
    requirements:
        id: \d+

book_index_api:
    path:     /api/v1/books/
    defaults: { _controller: "LybraryBundle:Api:index", _format: "json" }
    methods:  GET

book_add_api:
    path:     /api/v1/books/add/
    defaults: { _controller: "LybraryBundle:Api:add", _format: "json" }
    methods:  [GET, POST]

book_edit_api:
    path:     /api/v1/books/{id}/edit
    defaults: { _controller: "LybraryBundle:Api:edit", _format: "json" }
    methods:  [GET, POST]
    requirements:
        id: \d+