book_index:
    path:     /
    defaults: { _controller: "LybraryBundle:Book:index" }
    methods:  GET

book_show:
    path:     /{id}/show
    defaults: { _controller: "LybraryBundle:Book:show" }
    methods:  GET

book_new:
    path:     /new
    defaults: { _controller: "LybraryBundle:Book:new" }
    methods:  [GET, POST]

book_edit:
    path:     /{id}/edit
    defaults: { _controller: "LybraryBundle:Book:edit" }
    methods:  [GET, POST]

book_delete:
    path:     /{id}/delete
    defaults: { _controller: "LybraryBundle:Book:delete" }
    methods:  DELETE
